### ISSUE TITLE
Revise Where to Buy Functionality

### ISSUE THREAD

**Issue by ninnemana** [aries-auto/ariesautomotive#87] opened 2015-12-18 20:59 UTC
Make the search field more prominent and enabled without GeoLocation API.

**Comment by ninnemana** [comment] 2016-01-08 17:20
Below is some of the feed back for changes requested:

	
- Improve Performance: Loading the map initially takes longer than expected.​
- Work towards making the map driven by zip code instead of location services.
- Prioritize Discount Hitch as top result when he is in the results​
- Levels (similar to CURT:Silver Gold Platinum) - 
    - Organize in buckets and mirror CURT's Platinum/gold/Silver
    - Tiered images for different levels on the map-do not show platinum if no platinum dealers exist in the area. 
    - Do not show the category if there are no customers in the category.  (BIG FLAG, smaller red dot, tiny red dot)

**Comment by DavidVaini** [comment] 2016-01-15 15:00
Quick question, what do they mean by not showing the "category" if there are no customers in the category?  I am assuming you mean Tiers (Platinum, Gold, Silver), or am I completely off base? 

Not looking for any insight, just want clarification on customer's requirements

**Comment by DavidVaini** [comment] 2016-01-15 15:06
For future reference, I got the answer yes, I guess just the "(Big Flag, smaller red dot, tiny red dot)" confused me.

**Comment by DavidVaini** [comment] 2016-01-21 16:31
UPDATE:

You can see my progress on http://2.aries-auto.appspot.com/buy

I opted to keep AutoComplete, but I allow you to type in a zip code and hit enter to override the auto complete.

One of the reasons why the initial load was slow is because it was waiting to show the map until the browsers geolocation services got the geolocation (a few seconds of loading). I disabled waiting for that and the map loads very quickly now. The downside is once the geolocation is found, it changes the map's location to that new spot. I was thinking about having a loading geolocation message hovering over the map, but still not sure about that.

You can now toggle different tiers, however almost every spot on the map is platinum currently. As you move the map the list below the map changes. I got rid of the top 4 system because we are now doing the tier system. This of course made the map larger and more similar to the way CURT MFG has it.

In regards to the online retailer, I opted to show the tiers and I wrote up a quick little blurb about the page since it didn't have a heading or explanation before. I also am thinking it might be beneficial to have platinums have their company logo/banner  instead of their company name. (We could do both). Currently none of the platinum online retailers have their logo inserted into the database. When a logo is not present, it will display the name like the gold and silver tiers.

I still have to work on prioritizing discount hitch in the results.

**Comment by mickelsonm** [comment] 2016-01-21 22:52
Another bug you should be aware of in regards to Where to Buy functionality...

There's a problem with the dialog box prompting you for a zip code and using the back button.

Steps to reproduce: 

1. When first prompted for the Zip Code, close it by clicking on the X.
2. Navigate to another page like Contact.
3. Navigate to Where to Buy. (notice the dialog box comes back)
4. Click the Back Button.

Notice how the dialog box is still there and even if you do fill in a valid zip code it doesn't retain that information when you finally click on the Search button.

Thought you guys should know!

**Comment by DavidVaini** [comment] 2016-01-22 14:51
Thanks @mickelsonm.

Update: The Discount Hitch stuff was added. I also added a loading dialog for when getting geoLocation takes awhile.

I am going to talk to Chris today (If he has time :eyes:) and ask about Platinum Online Retailer Images and for him to try the new revised WTB

**Comment by DavidVaini** [comment] 2016-01-22 22:22
I think the new WTB is pretty good. I fixed @mickelsonm's issue in my version but not the live version. 

After talking to Chris about the Platinum Online Retailer Images, it seems like he is against it. It was not in the original list of feedback, just a little idea I had to make Platinum Stand out and to create more incentive for our gold dealers to try to work up to Platinum.

With that being said, all of the things on the initial feedback is done. It would be nice to get some more people looking at it for further review as I am sure there will be changes requested.

**Comment by ninnemana** [comment] 2016-01-22 22:29
Well I would say not to trigger the geolocation lookup unless they click something to tell you to use geolocation.

http://www.homedepot.com/StoreFinder/

HomeDepot must being doing a geo lookup on the IP address of the client to get a starting point though. (That's a though)

**Comment by DavidVaini** [comment] 2016-01-25 14:36
I thought about using IP address as a starting point, the downside is that you need to use a third party to fetch geolocation based off the IP address. There are some free ones, but the ones I have found so far says if you are using it on a larger application then you need to get licensing. Alternatively I could pick Eau Claire WI as the default starting point and have a button to activate geo location (like the homedepot example above).

**Comment by ninnemana** [comment] 2016-01-25 15:07
This doesn't work?

`curl -d '' https://www.googleapis.com/geolocation/v1/geolocate?key=[google maps key]`

**Comment by DavidVaini** [comment] 2016-01-25 15:30
Didnt find that when searching for google geolocation ip address lookup. Only thing I found, was google suggesting not to use IP addresses here:
https://developers.google.com/maps/articles/geolocation

Good to know, i'll give it a try though.

**Comment by DavidVaini** [comment] 2016-01-26 21:01
I recently incorporated the IP address lookup. It attempts to load the location via IP address. If this fails, the default location is Eau Claire. If at any time someone wants to use the Browser's GeoLocation Service, they can do so by clicking the button (Use Your Location).

The initial load time is much faster than the original one, and requires the user to opt in if they want to use the browsers geo location, very similar to how homedepot has their map setup.

Overall I think I like this setup over the previous way.

If you guys have any suggestions/changes/bugs, please feel free to let me know.

**Comment by ninnemana** [comment] 2016-02-04 18:14
I made some minor changes to layout, moved the `Use my Location` next to the search bar, put a background on the text locations, bordered the tier titles, and fix some floating problems.

5a551675ac842a90335efe6ebbe7a51af15f4c06
83306971c5ddb7fba8e7ab5798d1a9908286be8b

Going to send out for review.

**Comment by ninnemana** [comment] 2016-02-18 21:28
Has the sort order of the tiers been fixed? There was a big where once in awhile it wasn't going in the order of Platinum -> Silver -> Gold

**Comment by DavidVaini** [comment] 2016-02-18 21:34
No, I have not been able to replicate, and the logic seems sound (it has group filtering on the view).  Was there a specific location you were looking at to get it to be out of order?

**Comment by DavidVaini** [comment] 2016-02-18 21:36
Also, you mentioned off hand that there was to be an update to the flag or something along those lines, do we have the updated image?

**Comment by ninnemana** [comment] 2016-02-18 21:38
I already implemented the new map image. 

![image](https://cloud.githubusercontent.com/assets/187030/13159067/91aabeba-d655-11e5-803d-141bf4e1f0a2.png)

I loaded the map then zoomed out, in, and back out again.

**Comment by DavidVaini** [comment] 2016-02-22 14:25
the Dealer Tier problem has been fixed with this commit:
https://github.com/aries-auto/ariesautomotive/commit/07b4d9535153f39fe9e4c16a8a2d3388b710e462

**Comment by ninnemana** [comment] 2016-03-17 19:06
Looks like the `Silver` tier isn't being displayed, an example location that should populate `Silver` is `Cerritos, CA 90703`

**Closed** 2016-03-18 15:51 UTC
Labels: 3 - Review, enhancement
