### ISSUE TITLE
ARIES Category Page Anchor Tags

### ISSUE THREAD

**Issue by aaronrodgersmoustache** [aries-auto/ariesautomotive#237] opened 2016-11-21 23:10 UTC
The links in the ARIES category pages that are supposed to direct to anchors within the same page do not appear to be working properly. When I click them, it defaults to the top of the page.

**Comment by DavidVaini** [comment] 2016-11-29 19:57
The Anchor Tags work when Javascript is disabled. I noticed the page rerenders after the anchor tag has been triggered. This is being caused by the site being re-rendered, this should be fixed once https://github.com/aries-auto/ariesautomotive/issues/235
is fixed.

**Comment by shakilcfg** [comment] 2016-12-19 19:48
Have to move to IA prioritization before holidays

**Comment by DavidVaini** [comment] 2016-12-19 19:51
this was actually completed when #235 was fixed. Closing issue.

**Closed by DavidVaini** 2016-12-19 19:51 UTC
Labels: bug, help wanted
